### ISSUE TITLE
Push a release?

### ISSUE THREAD

**Issue by akhilles** [fnichol/names#6]
Would it be possible to push a new release to crates.io? The latest release still depends on `rand ^0.3.0`.

**Comment by fnichol** [comment]
Hi @akhilles!

I apologize for missing this over the summer, and I agree! I started indirectly working on this in #7 which in addition to updating dependencies, adds many CI and release-related goodies such as:

* Migrating from Travis CI to [Cirrus CI](https://cirrus-ci.com/)
* Supporting build and test on Linux, macOS, FreeBSD, & Windows
* Binary release artifacts for the above and several additional Linux targets via cross-compilation including a statically compiled Linux/musl target
* Collapsing the crate library and CLI into one crate that ships both concerns via Cargo features
* A default CLI build, allowing for `cargo install names`

This turned out to be a rather large bundle of work, but as I'll be using this as a common project platform, it should be worth it.

I will make sure to close this out once the next release is out the door, which I'm hoping is soon now that I've tamed the Windows beast (yet again).

**Comment by chevdor** [comment]
That would indeed nice to release a new version and free all projects depending on this crate from those old `rand` dependencies :)

**Comment by fnichol** [comment]
Ah yes, thank you for the reminder and sorry that this slipped my mind for more than a few months.

Long story short is this is ready to go, so I'll fire up a release once #11 merges clean.

**Comment by fnichol** [comment]
Well…I would have preferred that a release PR closed this, so I'll re-open to officially close when we're done 🎉

**Comment by fnichol** [comment]
Version [0.12.0](https://crates.io/crates/names/0.12.0) is out the door
